/**
 * expose-sidebars
 *
 * Tiny Docusaurus plugin that takes the resolved sidebars from
 * `docusaurus-plugin-content-docs` and exposes them as plugin global data
 * so non-doc pages (e.g. the homepage drawer) can render the same nav
 * tree as the inline doc sidebar — without maintaining a hand-coded copy
 * of `sidebars.ts`.
 *
 * Resolves doc-id refs to permalinks using the loaded docs metadata.
 * Also handles `{type: 'category', link: {type: 'doc', id: '...'}}` by
 * surfacing an `href` on the category.
 *
 * In SiteNav (or any client component), read it via:
 *
 *   import {usePluginData} from '@docusaurus/useGlobalData';
 *   const {mainSidebar} = usePluginData('expose-sidebars');
 */

module.exports = function exposeSidebarsPlugin() {
  return {
    name: 'expose-sidebars',

    // Use allContentLoaded so we can read other plugins' content
    // (in particular docusaurus-plugin-content-docs).
    async allContentLoaded({ allContent, actions }) {
      const docsContent = allContent['docusaurus-plugin-content-docs']?.default;
      const version = docsContent?.loadedVersions?.[0];
      if (!version) {
        actions.setGlobalData({ mainSidebar: [] });
        return;
      }

      // Build id → {permalink, label} map for fast lookup
      const docInfo = new Map();
      for (const doc of version.docs ?? []) {
        const label =
          doc.frontMatter?.sidebar_label ??
          doc.sidebar_label ??
          doc.title ??
          doc.id;
        docInfo.set(doc.id, { permalink: doc.permalink, label });
      }

      // Carry these through unchanged on every item so theme-level styling
      // (e.g. `.menu__list-item.hidden` for hidden entries) and arbitrary
      // user metadata still apply in the homepage drawer.
      const passThrough = (item) => ({
        ...(item.className !== undefined ? { className: item.className } : {}),
        ...(item.customProps !== undefined ? { customProps: item.customProps } : {}),
      });

      const resolve = (items) =>
        (items ?? []).map((item) => {
          if (item.type === 'doc' || item.type === 'ref') {
            const info = docInfo.get(item.id);
            return {
              type: 'link',
              label: item.label ?? info?.label ?? item.id,
              href: info?.permalink ?? `#missing-${item.id}`,
              docId: item.id,
              ...passThrough(item),
            };
          }
          if (item.type === 'link') {
            return {
              type: 'link',
              label: item.label,
              href: item.href,
              ...passThrough(item),
            };
          }
          if (item.type === 'category') {
            // Category may carry a link → resolve to href.
            let href;
            if (item.link?.type === 'doc' && item.link.id) {
              href = docInfo.get(item.link.id)?.permalink;
            } else if (item.link?.type === 'generated-index' && item.link.permalink) {
              href = item.link.permalink;
            }
            return {
              type: 'category',
              label: item.label,
              collapsible: item.collapsible !== false,
              collapsed: item.collapsed !== false,
              ...(href ? { href } : {}),
              ...passThrough(item),
              items: resolve(item.items),
            };
          }
          // html / autogenerated (already expanded by Docusaurus) / unknown
          return item;
        });

      const mainSidebarRaw = version.sidebars?.mainSidebar ?? [];
      actions.setGlobalData({
        mainSidebar: resolve(mainSidebarRaw),
      });
    },
  };
};
